export const sampleData = [
  {
    category: "Electronics",
    product: "Smartphone",
    region: "North",
    sales: 1200,
    profit: 450,
    units: 120,
    year: 2023,
    quarter: "Q1",
  },
  {
    category: "Electronics",
    product: "Laptop",
    region: "North",
    sales: 2500,
    profit: 800,
    units: 50,
    year: 2023,
    quarter: "Q1",
  },
  {
    category: "Electronics",
    product: "Tablet",
    region: "South",
    sales: 800,
    profit: 300,
    units: 80,
    year: 2023,
    quarter: "Q1",
  },
  {
    category: "Furniture",
    product: "Desk",
    region: "East",
    sales: 1500,
    profit: 600,
    units: 30,
    year: 2023,
    quarter: "Q1",
  },
  {
    category: "Furniture",
    product: "Chair",
    region: "West",
    sales: 900,
    profit: 350,
    units: 90,
    year: 2023,
    quarter: "Q1",
  },
  {
    category: "Office Supplies",
    product: "Paper",
    region: "North",
    sales: 400,
    profit: 100,
    units: 200,
    year: 2023,
    quarter: "Q2",
  },
  {
    category: "Office Supplies",
    product: "Pens",
    region: "South",
    sales: 250,
    profit: 80,
    units: 500,
    year: 2023,
    quarter: "Q2",
  },
  {
    category: "Electronics",
    product: "Smartphone",
    region: "East",
    sales: 1400,
    profit: 520,
    units: 140,
    year: 2023,
    quarter: "Q2",
  },
  {
    category: "Electronics",
    product: "Laptop",
    region: "West",
    sales: 2200,
    profit: 750,
    units: 45,
    year: 2023,
    quarter: "Q2",
  },
  {
    category: "Furniture",
    product: "Bookshelf",
    region: "North",
    sales: 1100,
    profit: 400,
    units: 25,
    year: 2023,
    quarter: "Q2",
  },
  {
    category: "Electronics",
    product: "Smartphone",
    region: "South",
    sales: 1300,
    profit: 480,
    units: 130,
    year: 2023,
    quarter: "Q3",
  },
  {
    category: "Electronics",
    product: "Laptop",
    region: "East",
    sales: 2700,
    profit: 900,
    units: 55,
    year: 2023,
    quarter: "Q3",
  },
  {
    category: "Furniture",
    product: "Sofa",
    region: "West",
    sales: 3000,
    profit: 1200,
    units: 15,
    year: 2023,
    quarter: "Q3",
  },
  {
    category: "Office Supplies",
    product: "Stapler",
    region: "North",
    sales: 150,
    profit: 50,
    units: 100,
    year: 2023,
    quarter: "Q3",
  },
  {
    category: "Office Supplies",
    product: "Binder",
    region: "South",
    sales: 300,
    profit: 120,
    units: 150,
    year: 2023,
    quarter: "Q3",
  },
]

